apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-a
spec:
  workspaces:
    - name: ws-a-1
    - name: ws-a-1-optional-1
      optional: true
    - name: ws-a-optional-2
      optional: true
    - name: ws-a-missed
  params:
    - name: param-a-with-default
      default: param1
    - name: param-a
      type: array
    - name: param-a-missed
  steps:
    - image: ubuntu
      script: echo 'hello there'

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-finally
spec:
  workspaces:
    - name: ws-finally-1
    - name: ws-finally-optional-1
      optional: true
    - name: ws-finally-optional-2
      optional: true
    - name: ws-finally-missed
  params:
    - name: param-finally-with-default
      default: param-finally
    - name: param-finally-missed
  steps:
    - image: ubuntu
      script: echo 'hello there'
